//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDoctor()
        {
            this.tblPatients = new HashSet<tblPatient>();
        }
    
        public int DoctorID { get; set; }
        public string NameSurname { get; set; }
        public string BLK { get; set; }
        public int Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public int UniqueNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Department { get; set; }
        public int ShiftInWhichHeWorks { get; set; }
        public int ResponsiblePatientAdmission { get; set; }
        public Nullable<int> SuperiorManager { get; set; }
    
        public virtual tblGender tblGender { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblShiftWork tblShiftWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatient> tblPatients { get; set; }

        public string DoctorDetails
        {
            get
            {
                return "ID: " + UniqueNumber + ", " + NameSurname + ", " + Department; 
            }
        }
    }
}
