//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public int PatientID { get; set; }
        public string NameSurname { get; set; }
        public string BLK { get; set; }
        public int Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public string HealthInsuranceCardNumber { get; set; }
        public System.DateTime ExpirationDateHealthInsurance { get; set; }
        public Nullable<int> UniqueNumberDoctor { get; set; }
    
        public virtual tblDoctor tblDoctor { get; set; }
        public virtual tblGender tblGender { get; set; }
    }
}
