//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDailyMaintenance
    {
        public int DailyMaintenanceID { get; set; }
        public System.DateTime DateMaintenance { get; set; }
        public int WorkingTime { get; set; }
        public string DescriptionMaintenance { get; set; }
        public int Maintenance { get; set; }
        public int MainternaceID { get; set; }
        public string NameSurname { get; set; }
        public string BLK { get; set; }
        public System.DateTime DateOfBirth { get; set; }
    }
}
