//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalInstitution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDoctor
    {
        public int DoctorID { get; set; }
        public string NameSurname { get; set; }
        public string BLK { get; set; }
        public int Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Citizenship { get; set; }
        public string UsernameLogin { get; set; }
        public string PasswordLogin { get; set; }
        public int UniqueNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Department { get; set; }
        public int ShiftInWhichHeWorks { get; set; }
        public Nullable<int> SuperiorManager { get; set; }
        public int ResponsiblePatientAdmission { get; set; }
        public int ShiftWorksID { get; set; }
        public string ShiftWorks { get; set; }
        public int GenderID { get; set; }
        public string GenderSign { get; set; }
        public string Expr1 { get; set; }
        public int ManagerID { get; set; }
        public string Expr2 { get; set; }
        public int FloorInstitution { get; set; }
        public int MaxNumSupervising { get; set; }
        public int NumOmissions { get; set; }
        public int MinNumRoomSupervised { get; set; }
    }
}
